[project]
name = "arepytools"
description = "ArePyTools is the Aresys Python toolset for SAR data processing."
authors = [{ name = "Aresys S.R.L.", email = "info@aresys.it" }]
license = { file = "LICENSE.txt" }
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "License :: OSI Approved :: MIT License",
]
requires-python = ">= 3.9"
dependencies = ["xsdata", "lxml", "python-dateutil", "scipy", "numpy >= 1.20"]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["nox", "ruff", "pylint"]
test = ["unittest-xml-reporting", "coverage"]
doc = [
    "ipython",
    "nbsphinx",
    "sphinx",
    "sphinx-design",
    "sphinx-copybutton",
    "pydata-sphinx-theme",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "arepytools/__init__.py"

[tool.hatch.build.targets.sdist]
only-include = ["arepytools", "tests", "docs"]

[tool.pdm.scripts]
format_check = "ruff format --check"
format = "ruff format"
sort = "ruff check --select I --fix-only"
lint_check = "ruff check"
lint_fix = "ruff check --show-fixes --fix-only"
test = "python -m unittest discover -s ./tests -p test_*.py"
clean_doc = "python -m sphinx -M clean docs/source {args}"
build_doc = "python -m sphinx -b html docs/source {args}"
check_code = { composite = ["format_check", "lint_check"] }
fix_format = { composite = ["format", "sort", "lint_fix"] }

[tool.pdm.resolution]
respect-source-order = true

[tool.ruff]
line-length = 120
output-format = "grouped"
extend-exclude = [
    ".venv",
    "xsd",
    "docs",
    "benchmarks",
    "arepytools/constants.py",        # deprecated
    "arepytools/io/channel.py",       # deprecated
    "arepytools/io/productfolder.py", # deprecated
    "arepytools/geometry/wgs84.py",   # deprecated
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "W", "F", "A", "B", "I"]
exclude = [
    "arepytools/io/metadata_models/translate.py", # planned rewriting
    "arepytools/io/metadata.py",                  # planned rewriting 
]
ignore = ["A005"]

[tool.pylint.MASTER]
extension-pkg-allow-list = "lxml"
ignore = [
    "aresys_types.py",
    "aresys_generic_metadata.py",
    "aresys_point_target_models.py",
    "channel.py",
    "productfolder.py",
    "wgs84.py",
]
fail-under = 8.0

[tool.pylint.FORMAT]
max-line-length = 120
